s1 = int(input("Enter marks of roll no. 1 :  "))
s2 = int(input("Enter marks of roll no. 2 :  "))
s3 = int(input("Enter marks of roll no. 3 :  "))
s4 = int(input("Enter marks of roll no. 4 :  "))
s5 = int(input("Enter marks of roll no. 5 :  "))
s6 = int(input("Enter marks of roll no. 6 :  "))
s7 = int(input("Enter marks of roll no. 7 :  "))
myMarksList = [s1,s2,s3,s4,s5,s6,s7]
myMarksList.sort()
print(myMarksList)